### ISSUE TITLE
Bidirectional data flow has unidirectional arrow

### ISSUE THREAD

**Issue by srcnuzn** [Threagile/threagile#94]
**Version**
Version: 1.0.0 (20240730113903)

**Steps to reproduce**

Have technical assets with communication link where data assets are sent and received.

```yaml
    communication_links:
      Compile Model:
        target: my-server
        description: Server processing stuff...
        protocol: https
        . . .
        data_assets_sent:
          - some-asset
        data_assets_received:
          - some-other-asset
```

**Expected:**

If I define `data_assets_sent` and `data_assets_receive`, I expect a bidirectional arrow.

**Actual:**

Arrow is unidirectional.

![image](https://github.com/user-attachments/assets/325162cc-daff-4de0-911a-bc6e7d9cb610)
